language: go
go:
- 1.10.x

sudo: false

install:
- go get -t -v ./...

script:
- make test

after_success:
  - test ${TRAVIS_TAG:0:1} = v && curl -sL https://git.io/goreleaser | bash

notifications:
email: false